### ISSUE TITLE
Module cheveches : installation

### ISSUE THREAD

**Issue by etot** [PnCevennes/protocoles_suivi#2]
Bonjour,
dans /cheveches/module.json il y a une virgule en trop qui bloque l'installation.
Cordialement

**Comment by amandine-sahl** [comment]
Merci pour l'information. C'est corrigé
Par ailleurs nous ne sommes pas pleinement du rendu de ce module. Il faudrait rajouter le niveau groupe de site
cf : https://github.com/PnX-SI/gn_module_monitoring/issues/24
