### ISSUE TITLE
[POPAmphibien]&[POPReptile]: créer une nouvelle aire

### ISSUE THREAD

**Issue by cen-cgeier** [PnCevennes/protocoles_suivi#7]
Bonjour, 
j'ai installé les protocoles POPAmphibien et POPReptile sur mon GéoNature 2.9.1 mais je ne parviens pas à créer une nouvelle aire. Le leaflet ne donne pas la possibilité d'importer ou de définir des points GPS.
En cherchant dans les fichiers du module, je ne trouve pas la/les raison(s) de ce souci. Une idée !??
D'avance merci !
![image](https://user-images.githubusercontent.com/96542451/152192372-eba1c0f6-9462-47b1-8376-3b6dfcc24c53.png)

**Comment by camillemonchicourt** [comment]
J'ai installé tous les modules d'exemple sur la serveur de démo https://demo.geonature.fr/geonature/#/monitoring avec la version 1.1.7 du module d'Import et j'ai constaté le même soucis.
La console du navigateur semble donner des pistes : 

```
ERROR TypeError: Cannot read properties of undefined (reading 'map')
```

Mais je ne suis pas capable de les interpréter.

Il doit y avoir un petit soucis avec les aires dans la version 1.1.7 du module, ou alors une évolution de GeoNature à répercuter dans le module ou dans la conf de ce sous-module.

**Comment by cen-cgeier** [comment]
Premier élément de réponse ! 
Il semble que le problème provienne de l'imbrication de la clé `site` dans la clé `sites_group` au sein du fichier config.json du module POPAmphibien.
Il semble que la structuration correcte de ce fichier ressemble à ce qui suit :
`{
  "tree": {
    "module": {
      "site": {
        "visit": {
          "observation": null
        }
      },
      "sites_group": null
    }
  }
}` 

Mais forcément, la résolution d'un problème en soulève un autre !! ^^' 
Il n'est pas possible de créer un passage sur l'aire enregistrée. Le bouton de validation ne s'active pas alors que tous les champs sont remplis. 
Le même message d'erreur, est communiqué par chrome : 
`ERROR TypeError: Cannot read properties of undefined (reading 'map')`

**Comment by maximetoma** [comment]
Salut, pour apporter de l'eau au moulin :)

J'ai testé et je pense avoir identifié le problème:
En enlevant l'`id_dataset` du fichier `sites_group.json`, tout se déroule sans soucis !

J'ai l'impression que c'est la position de cet item qui a l'air de poser problème....

**Comment by cen-cgeier** [comment]
> [EDIT]: Ce qui pose problème c'est le type_widget de id_dataset !
Il faut remplacer datalist par dataset

Salut Maxime,
il me semble que c'est le  `"data_path": "data",` qui pose problème.
Le `"type_widget": "datalist"` fonctionne chez moi pour l'objet `id_dataset`.

Au cours de mon premier post dans cette issue, je souhaitais pouvoir dessiner un groupe de site correspondant à une zone d'étude ou à un site géré. 
En ajoutant la variable `geometry_type` au fichier sites_group.json, l'applicatif permet de saisir une géométrie et ne fournit pas de message d'erreur à la validation. Par contre, la BDD ne permet pas de stocker la géométrie dans la table t_sites_groups. il n'y a pas de champs prévu pour. Ce sera peut-être envisagé à l'avenir...
La conséquence est qu'on ne peut pas encore définir de géométrie de groupe de sites. 

J'ai tenté de pallier à cela en passant par des géométries stockées dans la table `l_area`. 
La variable `sites_group_name` du fichier sites_group.json était une datalist des zones souhaitées. Cela fonctionne, néanmoins, je ne parviens pas à faire afficher la géométrie de la zone dans le leaflet, ni dans l'export pdf ...

**Comment by cen-cgeier** [comment]
> [EDIT 2]: dataset verse tous les JDD et pas seulement celui renseigné au sous-module
Je continue de creuser....

`id_dataset` tel que défini dans le fichier `gn_module_monitoring/config/monitoring/generic/visit.json` permet de renvoyer seulement les JDDs définis dans les paramètres du module.
Voici la config que j'ai et qui fonctionne chez moi : 

"id_dataset":` {   

      "type_widget": "datalist",
      "attribut_label": "Jeu de données",
      "type_util": "dataset",
      "api": "meta/datasets",
      "application": "GeoNature",
      "keyValue": "id_dataset",
      "keyLabel": "dataset_shortname",
      "params": {
        "orderby": "dataset_name",
        "module_code": "__MODULE.MODULE_CODE"
      },
      "required": true
    }
