### ISSUE TITLE
INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by cen-cgeier** [PnCevennes/protocoles_suivi#9]
Bonjour à tous,

je tente actuellement de créer un module de suivi. Il s'installe correctement et les logs ne communiquent pas. Je me dis donc que tout se passe bien ...
Pourtant lorsque je tente d'accéder au module, le formulaire ne s'affiche pas et le code source de la page indique une erreur 500.
![image](https://user-images.githubusercontent.com/96542451/161282210-d43d264b-7e45-448b-930d-d0ac5a472d9d.png)

Le module que je tente d'installer s'intitule RHOMEOAmphibien et se trouve dans un fork :  https://github.com/cen-cgeier/protocoles_suivi
Version GeoNature : 2.9.2
Version Monitoring  : 0.2.9

Auriez-vous des pistes sur une erreur que j'aurais pu commettre ?

**Comment by camillemonchicourt** [comment]
Je crois que vous n'avez pas posté le ticket sur le bon dépôt. 
Ici il s'agit du dépôt de partage d'exemple de sous-modules et non pas du module Monitoring concerné par votre problème ?

**Comment by joelclems** [comment]
cela pourrait être une erreur dans les fichiers de configuration json
est ce que vous avez plus d'information dans les logs ?

**Comment by cen-cgeier** [comment]
> cela pourrait être une erreur dans les fichiers de configuration json est ce que vous avez plus d'information dans les logs ?

Je pense aussi que ça provient de là mais je ne parviens pas à trouver l’erreur ..
Je n'ai pas trouvé d'info dans les fichiers de logs ..  
Rien dans var/log/gn_errors.log, ni dans var/log/geonature.log, ni dans /var/log/apache2/geonature_error.log, ni dans /var/log/apache2/geonature_access.log.

**Comment by cen-cgeier** [comment]
Je cherchais mon log geonature.log dans mon dossier ~/geonature/var/log et non dans /var/log à la racine de mon serveur. Désolé pour cette confusion..
Voici mes logs : 
> [2022-04-06 14:04:09 +0200] [519274] [ERROR] Exception on /monitoring/config/RHOMEOAmphibien [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/config.py", line 22, in get_config_api
    return get_config_frontend(module_code, force=True)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 241, in get_config_frontend
    config = dict(get_config(module_code, force))
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 162, in get_config
    config['data'] = get_data_preload(config, module)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/utils.py", line 283, in get_data_preload
    out['nomenclature'].append(form['code_nomenclature_type'])
KeyError: 'code_nomenclature_type'

J'en déduis que mon erreur vient de la définition d'un des "code_nomenclature_type". Je les retrouves pourtant dans l'administration de mon instance.

**Comment by joelclems** [comment]
pour ces éléments

https://github.com/cen-cgeier/protocoles_suivi/blob/25eddeb348a8057da74b0e41c3b1d3d241876c20/RHOMEOAmphibien/site.json#L90-L107

il faut changer le type de widget et mettre `select` à la place de `nomenclature`

**Comment by cen-cgeier** [comment]
Effectivement, il serait même intéressant de retourner le nom du fichier et l'objet parent posant problème
